### ISSUE TITLE
How do you update?

### ISSUE THREAD

**Issue by johnjelinek** [Leon99/ChocolateyPackages#2]
I see update.bat isn't included here. How do you update your ini file?

**Comment by Leon99** [comment]
@johnjelinek Could you give me some context to your question (if it's still relevant to you)?

**Comment by johnjelinek** [comment]
You're missing some utils that are included in the zip: https://github.com/Leon99/ChocolateyPackages/blob/15a88aa4069d3548e97f5a9e1e11f58617d08d2f/rdpwrapper/tools/chocolateyinstall.ps1#L5

Downloading this without executing the utilities left me with an older version than expected.

**Comment by Leon99** [comment]
>You're missing some utils that are included in the zip:

All the content of this archive is extracted during the installation, not sure what you mean by "You're missing"

> Downloading this without executing the utilities left me with an older version than expected.

Not sure why it happened. If you check update.bat, all it does is `RDPWInst -w`, which is simply replicated in the install script: `https://github.com/Leon99/ChocolateyPackages/blob/15a88aa4069d3548e97f5a9e1e11f58617d08d2f/rdpwrapper/tools/chocolateyinstall.ps1#L11`
